apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: webapps
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089
  type: LoadBalancer