apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-container
          image: walidhsn/benhassouna_walid_tpfoyer:1.0.15
          ports:
            - containerPort: 8089
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
