apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
      version: stable  # Label for stable version
  template:
    metadata:
      labels:
        app: backend-app
        version: stable  # Label for stable version
    spec:
      containers:
        - name: backend-container
          image: walidhsn/benhassouna_walid_tpfoyer:1.0.12
          ports:
            - containerPort: 8089
          readinessProbe:
            httpGet:
              path: /health
              port: 8089
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8089
            initialDelaySeconds: 30
            periodSeconds: 10