version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=foyer_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-foyer:
    depends_on:
      - mysqldb
    image: walidhsn/benhassouna_walid_tpfoyer:1.0.30
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/foyer_db?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
          "spring.datasource.username": "root",
          "spring.datasource.password": "root",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    stdin_open: true
    tty: true

volumes:
  db: