name: Conditional Jenkins Trigger

on:
  push:
    branches:
      - master

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check commit message
        id: check_commit
        run: |
          EXCLUDED_PATTERNS="maven-release-plugin|Update Docker Compose|Update Backend deployment"
          LAST_COMMIT=$(git log -1 --pretty=%B)
          echo "Last commit message: $LAST_COMMIT"
          
          # Check if the commit matches any excluded pattern
          if [[ "$LAST_COMMIT" =~ $EXCLUDED_PATTERNS ]]; then
            echo "Excluded commit pattern found. Skipping Jenkins trigger."
            # Use exit 1 here to stop the pipeline and prevent any further steps
            exit 1
          fi
          echo "No excluded patterns found. Proceeding to trigger Jenkins."

      - name: Trigger Jenkins Webhook
        if: success()  # Proceed only if the previous step was successful
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          JENKINS_JOB_NAME: ${{ secrets.JENKINS_JOB_NAME }}
          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
        run: |
          curl -X POST "${JENKINS_URL}/job/${JENKINS_JOB_NAME}/build" \
               --user "${JENKINS_USERNAME}:${JENKINS_API_TOKEN}"
